import type { CSSProperties } from 'react';
import {
  AlarmClock,
  AlertTriangle,
  Armchair,
  ArrowLeft,
  ArrowUpRight,
  Bell,
  CalendarPlus,
  Camera,
  Check,
  CheckCircle2,
  ChevronRight,
  Coins,
  Crown,
  Flame,
  Gem,
  Gift,
  Home,
  Info,
  Lamp,
  LayoutDashboard,
  LifeBuoy,
  Map,
  Megaphone,
  Menu,
  MessageCircle,
  Minus,
  Package,
  PackageCheck,
  PartyPopper,
  Phone,
  Plus,
  QrCode,
  ReceiptIndianRupee,
  Repeat,
  Rocket,
  Search,
  Send,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Sticker,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Truck,
  UserPlus,
  Users,
  Vote,
  Wallet,
  Watch,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** kebab-case name → component, mirroring the prototype's <l-icon name="…"> */
const ICONS: Record<string, LucideIcon> = {
  'alarm-clock': AlarmClock,
  'alert-triangle': AlertTriangle,
  armchair: Armchair,
  'arrow-left': ArrowLeft,
  'arrow-up-right': ArrowUpRight,
  bell: Bell,
  'calendar-plus': CalendarPlus,
  camera: Camera,
  check: Check,
  'check-circle-2': CheckCircle2,
  'chevron-right': ChevronRight,
  coins: Coins,
  crown: Crown,
  flame: Flame,
  gem: Gem,
  gift: Gift,
  home: Home,
  info: Info,
  lamp: Lamp,
  'layout-dashboard': LayoutDashboard,
  'life-buoy': LifeBuoy,
  map: Map,
  megaphone: Megaphone,
  menu: Menu,
  'message-circle': MessageCircle,
  minus: Minus,
  package: Package,
  'package-check': PackageCheck,
  'party-popper': PartyPopper,
  phone: Phone,
  plus: Plus,
  'qr-code': QrCode,
  'receipt-indian-rupee': ReceiptIndianRupee,
  repeat: Repeat,
  rocket: Rocket,
  search: Search,
  send: Send,
  'share-2': Share2,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  sparkles: Sparkles,
  sticker: Sticker,
  target: Target,
  timer: Timer,
  'trending-up': TrendingUp,
  trophy: Trophy,
  truck: Truck,
  'user-plus': UserPlus,
  users: Users,
  vote: Vote,
  wallet: Wallet,
  watch: Watch,
  x: X,
  zap: Zap,
};

export interface IconProps {
  name: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: CSSProperties;
}

export function Icon({ name, size = 20, color = 'currentColor', strokeWidth = 2, style }: IconProps) {
  const C = ICONS[name];
  if (!C) return null;
  return <C size={size} color={color} strokeWidth={strokeWidth} style={{ flex: 'none', display: 'block', ...style }} />;
}
